### ISSUE TITLE
Problem when using with bulma installed by yarn

### ISSUE THREAD

**Issue by sinnedh** [jenil/bulmaswatch#2]
Hello,

thanks for your package. It is really great. I have a question:
when I'm installing both `bulma` and `bulmaswatch` with yarn the imports of `bulma` do not work, see e.g.
https://github.com/jenil/bulmaswatch/blob/gh-pages/default/bulmaswatch.scss#L3

Replacing the import
`@import "bulma";`
by
`@import "~bulma";`
solves the problem but this is probably not the best solution.

Is there a way how to handle this in a more elegant way?

Best,
Dennis

**Comment by jenil** [comment]
Hey,

Thanks for using Bulmaswatch.

You're right, the build is failing because it can't find the `@import "bulma";`

I assume you are using Webpack and that's why `@import "~bulma";` might work for you, but for Bulmaswatch I am building the themes using `gulp` and you need to have an [includePaths](https://github.com/jenil/bulmaswatch/blob/gh-pages/gulpfile.js#L63) so that sass can find the respective imports.

Thanks for bringing this up, I will find a better way to import `bulma` and build themes so they can be used from the npm package.

**Comment by jenil** [comment]
Hey @sinnedh 

I just published changes to the npm package with the new structure of the themes which should solve the missing import. Head to the [help](https://jenil.github.io/bulmaswatch/help/) page to read about customization with `yarn`/`npm`.

Cheers!

**Comment by sinnedh** [comment]
First of all, sorry for the late response. I was on vacation and also not watching this issue.

Thanks for the changes in the structure of the theme.

The solution with webpack would be, to replace: 
```
@import "~bulmaswatch/flatly/bulmaswatch.scss";
```
with the separate imports:
```
@import "~bulma/bulma.sass";
@import "~bulmaswatch/flatly/_variables.scss";
@import "~bulmaswatch/flatly/_overrides.scss";
```

Did I understand this correctly?

**Comment by jenil** [comment]
@sinnedh it would be:

```scss
@import "~bulmaswatch/flatly/_variables.scss";
@import "~bulma/bulma.sass";
@import "~bulmaswatch/flatly/_overrides.scss";
```

**Comment by sinnedh** [comment]
You are right, thanks a lot!
