### ISSUE TITLE
journal theme: inconsistency in link color

### ISSUE THREAD

**Issue by obedm503** [jenil/bulmaswatch#50]
I noticed that there is an inconsistency when it comes to link colors. In bulmaswatch the headers ("# 14" and "# 16"), which are also links, are blue (`$blue`) while in bootswatch they're red (the `$primary` for this theme). 

Bulmaswatch left, bootswatch on the right
![image](https://user-images.githubusercontent.com/9118707/47040162-37940500-d14b-11e8-86ef-afb95872c5e8.png)

I can provide a pr if this is a desired fix, but I would like to know how to go about fixing it. There is certain incompatibility because bootstrap doesn't have a "link" color, it just uses its "primary" for links.  Bulma, on the other hand, separates link and primary into different colors. Should I just set `$link: $primary !default;`?

**Comment by jenil** [comment]
This was done intentionally since Bulma is a bit different than Bootstrap. Bulma has a `$link` color which need not necessarily be equal to `$primary`

![image](https://user-images.githubusercontent.com/971411/47045057-dc204200-d15f-11e8-8213-9f9679978263.png)

Feel free to override in your own file 🙂

**Comment by obedm503** [comment]
I wasn't sure if it was intentional. Thanks for the answer.
